name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["12", "14"]
    name: "[v${{ matrix.node-version }}] check"

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm ci
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ github.sha }}-node_modules-v${{ matrix.node }}

  check:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        node: ["12", "13"]
    name: "[v${{ matrix.node }}] check"

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ github.sha }}-node_modules-v${{ matrix.node }}

      - name: Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: |
          npm ci
      - name: Lint
        run: |
          npm run lint
      - name: Test
        env:
          CI: 1
        run: |
          npm t
      - name: Submit coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
